### ISSUE TITLE
Build sources

### ISSUE THREAD

**Issue by elpaxel** [Ossianaa/node-libcurl#7]
Hello. Thanks for the great library.

Can you show how you build curl (.lib/.dll) ?

**Comment by Ossianaa** [comment]
Another repository will be created later to display the source code.

**Comment by vitalygashkov** [comment]
> Another repository will be created later to display the source code.

Great library, thank you for your hard work. I was able to solve a problem in my project thanks to this library.

It's been over a year. Could you please share the source library for building *.a / *.dll / *.lib files?

I've encountered a bug #15, but it's not always convenient to wait for a fix from the library author. So it would be great to be able to fix the bug myself (and make a PR in your repository) so that my application using the library can work.

**Comment by Ossianaa** [comment]
Major patches have been uploaded to the [patches](https://github.com/Ossianaa/node-libcurl/tree/master/patches) directory.
